version: '2'

services:
  web:
    container_name: app_web
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/www/app:cached
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./site.conf:/etc/nginx/conf.d/default.conf
  php:
    container_name: app_php
    build:
      context: .
      args:
        - WITH_XDEBUG=true
      dockerfile: DockerfilePHP
    volumes:
      - ./app:/www/app:cached
      - ./composer.phar:/www/composer:cached
      - ./php.ini:/usr/local/etc/php/php.ini

  mariadb:
    container_name: app
    container_name: app_mariadb
    build:
      context: .
      dockerfile: DockerfileMariadb
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./volumes/mdbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: TravisRoot
      MYSQL_DATABASE: travis_app
      MYSQL_USER: tdeaton
      MYSQL_PASSWORD: ChangeMe!

volumes:
  mdbdata:
